version: "3.9"
services:
  medical_postgres:
    build: database/
    restart: always
    volumes:
      - type: bind
        source: ./database/postgres
        target: /var/lib/postgresql/data
    ports:
      - "127.0.0.1:5532:5432"
    expose:
      - "5432"
  backend:
    build: backend/
    restart: "always"
    ports:
      - "8000:8000"
    depends_on:
      - medical_postgres
    volumes:
      - "./backend/database:/app/database"
      - "./backend/:/app/backend"

volumes:
  backend: